# Generated by Django 5.0.6 on 2024-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('date_of_create', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(upload_to='Photos')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='Photos')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='Photos')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='Photos')),
                ('catalog', models.IntegerField(choices=[(1, 'Men'), (2, 'Women')])),
            ],
        ),
    ]
